chore: add new credential service
eclipse-tractusx/portal pull request #140
Opened 2024-01-08 09:39 UTC by Phil91

## Description

* add configuration for the new credential service
* adjust workflow file
* add values for new service for all environments

## Why

A new service has been added to the portal backend, to have the deployment and values available, the configuration has been added.

## Issue

N/A - JIra Issue: CPLP-3398

## Corresponding Backend PR

[#397](https://github.com/eclipse-tractusx/portal-backend/pull/397)

## Checklist

- [x] I have performed a self-review of my changes
- [x] I have successfully tested my changes
- [x] I have added comments in the default values.yaml file with helm-docs syntax ('# -- ') if relevant for installation
- [x] I have commented my changes, particularly in hard-to-understand areas

2024-01-08 16:16 UTC, evegufy requested changes
Could you please provide the feedback to Gitguardian that the discovered secret is a false positive?

2024-01-08 16:18 UTC, evegufy commented
Maybe the PR title would be better described with the prefix 'feat(ssi)' instead of chore.

2024-01-12 13:40 UTC, ntruchsess approved these changes

2024-04-04 19:24 UTC, Phil91 commented
Closing this PR. The changes are included in the new [ssi-credential-issuer](https://github.com/eclipse-tractusx/ssi-credential-issuer) repo

2024-04-04 19:24 UTC, closed without merging