feat(clearinghouse): add config for maintenance worker
eclipse-tractusx/portal pull request #418
Opened 2024-08-28 08:26 UTC by Phil91

## Description

add configuration of clearinghouse to the maintenance worker

## Why

To enable the maintenance worker to retrigger the clearinghouse process if the END_CLEARINGHOUSE step is in TODO for to long.

## Issue

Refs: https://github.com/eclipse-tractusx/portal-backend/issues/810

## Corresponding Backend PR

...

## Checklist

- [x] I have performed a self-review of my changes
- [x] I have successfully tested my changes
- [x] I have added comments in the default values.yaml file with helm-docs syntax ('# -- ') if relevant for installation
- [x] I have commented my changes, particularly in hard-to-understand areas

2024-09-12 16:55 UTC, evegufy requested changes

2024-09-13 06:19 UTC, Phil91 commented on charts/portal/templates/cronjob-backend-portal-maintenance.yaml
> +              - name: "CLEARINGHOUSE__RETRIGGERENCLEARINGHOUSEINTERVALINDAYS"
kudos for seeing that 🤯 👀

2024-09-13 06:20 UTC, Phil91 commented on charts/portal/templates/cronjob-backend-processes.yaml
> +            - name: "APPLICATIONCHECKLIST__CLEARINGHOUSE__RETRIGGERENCLEARINGHOUSEINTERVALINDAYS"
adjusted

2024-09-13 13:31 UTC, evegufy approved these changes

2024-09-17 11:37 UTC, merged