feature: Add configuration for stable environment
eclipse-tractusx/portal pull request #442
Opened 2024-10-07 07:37 UTC by ds-lcapellino

## Description

This PR will introduce environment specific configuration for the 24.08 release to run on the catena-x stable environment.

## Issue

relates to https://github.com/eclipse-tractusx/portal/issues/408

## Checklist

Please delete options that are not relevant.

- [ ] I have performed a self-review of my changes
- [ ] I have successfully tested my changes
- [ ] I have added comments in the default values.yaml file with helm-docs syntax ('# -- ') if relevant for installation
- [ ] I have commented my changes, particularly in hard-to-understand areas

2024-10-07 08:58 UTC, evegufy requested changes
Please fix secret path everywhere

2024-10-07 08:58 UTC, evegufy commented on environments/helm-values/values-stable.yaml
> +      clientSecret: "<path:portal/data.stable.iam/centralidp-client-secrets#reg-central-sa>"
```suggestion
      clientSecret: "<path:portal/data/stable/iam/centralidp-client-secrets#reg-central-sa>"
```

2024-10-07 13:12 UTC, ds-lcapellino commented on environments/helm-values/values-stable.yaml
> +      clientSecret: "<path:portal/data.stable.iam/centralidp-client-secrets#reg-central-sa>"
Fixed paths

2024-10-11 09:03 UTC, evegufy approved these changes

2024-10-16 07:18 UTC, evegufy commented
@ds-lcapellino as discussed, I'm closing this PR as it doesn't make sense to merge it main because there we're are already ahead of the v2.1.0, the branch can still be used for installing v2.1.0

2024-10-16 07:18 UTC, closed without merging